openapi: 3.0.1
info:
  title: Swagger CNC32
  description: 'This document aim to present all CNC32 API'
  termsOfService: http://swagger.io/terms/
  contact:
    email: yroffin@gmail.com
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/yroffin/grbl-cnc32/master/LICENSE
  version: 1.0.0
externalDocs:
  description: No data
  url: https://github.com/yroffin/grbl-cnc32
servers:
- url: http://localhost:8080/api
tags:
- name: configuration
  description: All configuration
  externalDocs:
    description: No data
    url: https://github.com/yroffin/grbl-cnc32
- name: i18n
  description: All i18n related
paths:
  /v1/config/config.json:
    put:
      tags:
      - configuration
      summary: Get the current configuration
      operationId: put-configuration
      requestBody:
        description: Configuration object for update operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
        required: true
      responses:
        200:
          description: Invalid ID supplied
          content: {}
        404:
          description: Pet not found
          content: {}
        405:
          description: Validation exception
          content: {}
    get:
      tags:
      - configuration
      summary: Get user by user name
      operationId: get-configuration
      parameters:
      - name: username
        in: path
        description: 'The name that needs to be fetched. Use user1 for testing. '
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
        400:
          description: Invalid username supplied
          content: {}
        404:
          description: User not found
          content: {}
components:
  schemas:
    Configuration:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
          default: false
